# Site settings
title: Alexis DeSousa
email: alexis@desousa.cc
description: > # this means to ignore newlines until "baseurl:"
  <i>Everything is theoretically impossible, until it is done. </i> -- Robert A. Heinlein
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alexis.desousa.cc" # the base hostname & protocol for your site
twitter_username: alexisleno
github_username:  alexisdesousa
facebook_username: alexis.b.desousa
banner: "/images/web_banner.png"
paginate: 5
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
