# Site settings
title: Alexis DeSousa
email: alexis@desousa.cc
description: > # this means to ignore newlines until "baseurl:"
  The new site of Alexis DeSousa
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alexis.desousa.cc" # the base hostname & protocol for your site
twitter_username: alexisleno
github_username:  alexisdesousa
facebook_username: alexis.b.desousa
banner: "/images/web_banner.png"
paginate: 5


# Build settings
markdown: kramdown
